### ISSUE TITLE
Failed to load the colorpicker package

### ISSUE THREAD

**Issue by myzen2** [ardcore/atom-colorpicker#11]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Unknown Windows Version
**Thrown From**: [colorpicker](https://github.com/ardcore/atom-colorpicker) package, v0.3.0
### Stack Trace

Failed to load the colorpicker package

```
At Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".


EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at Function (native)
    at installColorSpace (C:\Users\celin\.atom\packages\colorpicker\node_modules\onecolor\one-color-all-debug.js:97:32)
    at Object.<anonymous> (C:\Users\celin\.atom\packages\colorpicker\node_modules\onecolor\one-color-all-debug.js:218:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (C:\Users\celin\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at C:\Users\celin\.atom\packages\colorpicker\node_modules\colorjoe\dist\colorjoe.js:3:34
    at Object.<anonymous> (C:\Users\celin\.atom\packages\colorpicker\node_modules\colorjoe\dist\colorjoe.js:11:2)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (C:\Users\celin\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "sublime-default-syntax"
    ],
    "projectHome": "c:\\sites",
    "disabledPackages": [
      "semantic-ui",
      "icon-fonts",
      "file-type-icons",
      "unfancy-file-icons",
      "language-ruby"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
aligner-ruby, v1.4.0
atom-alignment, v0.12.1
atom-fix-path, v0.1.0
Atom-Hack, v6.1.5
atom-javascript-console-snippets, v0.10.0
Atom-Syntax-highlighting-for-Sass, v0.5.0
auto-id-class, v0.2.6
autoclose-html, v0.19.0
autocomplete-bibtex, v0.6.1
autocomplete-emojis, v2.2.2
autocomplete-glsl, v0.2.3
autocomplete-hack, v2.1.0
autocomplete-html-entities, v0.1.0
autocomplete-kdb-q, v0.4.1
autocomplete-modules, v1.3.0
autocomplete-motion, v2.1.0
autocomplete-paths, v1.0.2
autocomplete-ruby, v0.1.0
autocomplete-sass, v0.1.0
color-picker, v2.0.13
colorpicker, v0.3.0
default-language, v0.2.0
emmet, v2.3.13
file-icon-supplement, v0.8.3
file-icons, v1.6.11
go-to-view, v0.3.0
gtk-dark-theme, v0.1.4
hex, v0.6.2
html-entities, v0.4.0
language-b-html, v1.0.0
language-hack, v0.1.1
language-ruby-without-erb, v0.52.0
lg-silverstripe, v0.1.0
linter, v1.9.0
linter-erb, v0.1.1
linter-rails-best-practices, v0.2.2
linter-ruby, v1.2.0
linter-ruby-reek, v1.3.0
linter-xo, v0.8.0
minimap, v4.15.0
package-switch, v0.5.0
pigments, v0.18.0
rails-i18n, v0.1.3
remote-edit, v1.8.21
rubo-format, v0.3.0
ruby-block, v0.3.5
ruby-block-converter, v3.5.0
ruby-define-method, v0.2.2
ruby-slim, v0.2.0
ruby-syntax-replacer, v0.5.1
Sass-Syntax-Highlight, v0.1.1
set-syntax, v0.3.0
slim-language, v2.2.0
smart-tags, v0.1.0
sublime-default-syntax, v0.2.2
sublime-panes, v0.2.5
Sublime-Style-Column-Selection, v1.3.0
sublime-word-navigation, v0.1.2
tab-numbers, v0.3.0
tag, v0.3.0
terminal-panel, v1.14.1
terminal-plus, v0.12.1
terminal-status, v1.6.8

# Dev
No dev packages
```

**Comment by jjeroennl** [comment]
I have the same issue.
[Enter steps to reproduce below:]

1. Start up Atom

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11
**Thrown From**: [colorpicker](https://github.com/ardcore/atom-colorpicker) package, v0.3.0


### Stack Trace

Failed to load the colorpicker package

```
At Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".


EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at Function (native)
    at installColorSpace (/Users/j.tissink/.atom/packages/colorpicker/node_modules/onecolor/one-color-all-debug.js:97:32)
    at Object.<anonymous> (/Users/j.tissink/.atom/packages/colorpicker/node_modules/onecolor/one-color-all-debug.js:218:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at /Users/j.tissink/.atom/packages/colorpicker/node_modules/colorjoe/dist/colorjoe.js:3:34
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
colorpicker, v0.3.0
linter, v1.10.0
linter-php, v1.0.5
minimap, v4.16.0
pigments, v0.18.1
tool-bar, v0.1.9
tool-bar-main, v0.0.8

# Dev
No dev packages
```

**Comment by ghost** [comment]
I had the same issue. It seems this package isnt any longer maintained. I did uninstall atom-colorpicker and install color-picker instead: https://github.com/thomaslindstrom/color-picker

**Comment by Tikam02** [comment]
even in the updated version have the same problem
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Microsoft Windows 10 Home Single Language
**Thrown From**: [colorpicker](https://github.com/ardcore/atom-colorpicker) package, v0.3.0


### Stack Trace

Failed to load the colorpicker package

```
At Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".


EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at installColorSpace (F:\IDE\atom\AtomPortable\Data\atom\packages\colorpicker\node_modules\colorjoe\node_modules\onecolor\one-color-all-debug.js:97:32)
    at Object.<anonymous> (F:\IDE\atom\AtomPortable\Data\atom\packages\colorpicker\node_modules\colorjoe\node_modules\onecolor\one-color-all-debug.js:218:1)
    at Module._compile (F:\IDE\atom\AtomPortable\App\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (F:\IDE\atom\AtomPortable\App\Atom\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (F:\IDE\atom\AtomPortable\App\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at F:\IDE\atom\AtomPortable\Data\atom\packages\colorpicker\node_modules\colorjoe\dist\colorjoe.js:3:34
    at Object.<anonymous> (F:\IDE\atom\AtomPortable\Data\atom\packages\colorpicker\node_modules\colorjoe\dist\colorjoe.js:11:2)
    at Module._compile (F:\IDE\atom\AtomPortable\App\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (F:\IDE\atom\AtomPortable\App\Atom\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (F:\IDE\atom\AtomPortable\App\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///F:/IDE/atom/AtomPortable/Data/atom/packages/colorpicker/lib/colorpicker-view.coffee:1:12)
    at Object.<anonymous> (file:///F:/IDE/atom/AtomPortable/Data/atom/packages/colorpicker/lib/colorpicker-view.coffee:1:1)
    at Module._compile (F:\IDE\atom\AtomPortable\App\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (F:\IDE\atom\AtomPortable\App\Atom\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (F:\IDE\atom\AtomPortable\App\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///F:/IDE/atom/AtomPortable/Data/atom/packages/colorpicker/lib/colorpicker.coffee:1:19)
    at Object.<anonymous> (file:///F:/IDE/atom/AtomPortable/Data/atom/packages/colorpicker/lib/colorpicker.coffee:1:1)
    at Module._compile (F:\IDE\atom\AtomPortable\App\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (F:\IDE\atom\AtomPortable\App\Atom\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (F:\IDE\atom\AtomPortable\App\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (F:\IDE\atom\AtomPortable\App\Atom\resources\app.asar\src\package.js:721:27)
    at F:\IDE\atom\AtomPortable\App\Atom\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (F:\IDE\atom\AtomPortable\App\Atom\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (F:\IDE\atom\AtomPortable\App\Atom\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (F:\IDE\atom\AtomPortable\App\Atom\resources\app.asar\src\package-manager.js:457:14)
    at PackageManager.module.exports.PackageManager.activatePackage (F:\IDE\atom\AtomPortable\App\Atom\resources\app.asar\src\package-manager.js:536:30)
    at F:\IDE\atom\AtomPortable\App\Atom\resources\app.asar\node_modules\settings-view\lib\package-manager.js:460:29
    at exit (F:\IDE\atom\AtomPortable\App\Atom\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (F:\IDE\atom\AtomPortable\App\Atom\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (F:\IDE\atom\AtomPortable\App\Atom\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

### Commands

```
  2x -8:06.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -7:54.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:04.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -5:54.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 15x -2:02.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:58.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 15x -1:39.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:26.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "file-icons"
    ]
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.4 (inactive)
aligner-css, v1.2.0 (active)
aligner-javascript, v1.0.0 (active)
angular-2-typeScript-snippets, v0.6.3 (active)
angular2-snippets, v0.3.0 (active)
angular2-snippets-atom, v0.7.0 (active)
angularjs, v0.3.5 (active)
animate-css, v0.1.4 (active)
ariake-dark-syntax, v0.0.6 (inactive)
astronomical-ui, v0.22.5 (inactive)
atom-beautify, v0.29.13 (inactive)
atom-bemmet, v2.0.0 (inactive)
atom-code2html, v0.1.0 (inactive)
atom-css-class-checker, v0.4.3 (inactive)
atom-css-comb, v3.1.0 (inactive)
atom-css-unit-converter, v1.1.1 (inactive)
atom-darcula, v0.2.0 (inactive)
atom-htmltidy, v5.1.0 (active)
atom-idiomatic-comments-css-snippets, v0.1.0 (active)
atom-javascript-console-snippets, v0.10.0 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-ui, v1.3.8 (inactive)
atom-minify, v0.7.5 (active)
atom-monokai, v0.10.4 (inactive)
atom-react-native-css, v1.1.3 (active)
atom-snowflake-css, v0.1.1 (inactive)
atom-typescript, v10.1.13 (active)
aurora-theme, v1.2.2 (inactive)
autoclose-html, v0.23.0 (active)
autocomplete-html-entities, v0.1.0 (active)
ax-monokai-syntax, v0.1.0 (inactive)
colorblind-wombat-dark-syntax, v0.5.2 (inactive)
colorpicker, v0.3.0 (inactive)
css-clean, v2.15.0 (inactive)
css-color-underline, v1.0.1 (active)
css-comb, v2.5.0 (active)
css-declaration-sorter, v0.4.0 (inactive)
css-edit-groups, v0.4.2 (inactive)
css-from-html, v0.1.5 (inactive)
css-skeleton-maker, v0.1.4 (inactive)
css-snippets, v1.1.0 (active)
css-specificity, v0.2.2 (active)
css-spy, v0.6.0 (active)
css-to-inline, v1.1.0 (inactive)
css-triggers, v1.0.1 (active)
cssfmt, v1.4.0 (inactive)
darkula-ui, v0.1.0 (inactive)
dracula-theme, v1.2.8 (inactive)
dracula-ui, v0.3.0 (inactive)
eclipse-keybindings, v0.9.0 (active)
emmet, v2.4.3 (active)
emmet-jsx-css-modules, v1.0.0 (active)
es6-javascript, v1.0.0 (inactive)
eval-javascript, v1.2.0 (inactive)
export-html, v3.0.0 (inactive)
file-icons, v1.7.25 (inactive)
format-javascript-comment, v0.2.2 (active)
genesis-snippets, v2.1.0 (inactive)
Handlebars, v1.7.0 (active)
html-entities, v0.4.0 (active)
html-entitize, v1.1.0 (active)
html-head-snippets, v0.2.0 (active)
html-id-class-snippets, v1.4.1 (active)
html-nested-comments, v3.2.1 (inactive)
html-outliner, v0.1.1 (active)
html-tab, v1.0.2 (inactive)
html-to-css, v0.2.2 (inactive)
html-to-elm, v0.2.0 (inactive)
html-to-javascript, v0.2.0 (inactive)
html-to-string, v0.2.3 (inactive)
HTML2JS, v0.2.1 (inactive)
hydra-syntax-theme, v2.0.4 (inactive)
imdone-atom, v2.0.19 (active)
improved-asp-html, v1.8.1 (active)
javascript-object-snippets, v0.3.0 (active)
javascript-refactor, v0.5.5 (inactive)
javascript-snippets, v1.2.1 (active)
javascript-standard-snippets, v0.2.1 (active)
kuali-dark-ui, v1.0.0 (inactive)
language-asp-html, v0.2.0 (active)
language-b-html, v1.0.0 (active)
language-javascript-better, v1.7.1 (active)
language-javascript-jsx, v0.3.7 (active)
language-javascript-subtlegradient, v0.1.0 (active)
language-perl-html-template, v1.0.2 (active)
language-riot-tag, v0.2.2 (active)
language-ts, v1.0.2 (active)
language-typescript-grammars-only, v1.5.0 (active)
linter, v1.11.18 (active)
linter-spell-html, v0.6.1 (inactive)
linter-spell-javascript, v0.7.1 (inactive)
linter-tslint, v0.12.0 (active)
livescript-compile, v0.1.1 (active)
livestyle-atom, v0.2.7 (active)
Lucario, v2.0.0 (inactive)
meteor-api, v2.20.0 (active)
metro-syntax, v0.3.1 (inactive)
minimap, v4.26.4 (active)
minimap-bookmarks, v0.4.2 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-linter, v1.6.0 (active)
minimap-pigments, v0.2.2 (active)
minimap-selection, v4.4.0 (active)
monokai, v0.18.0 (inactive)
monokai-dark, v1.3.0 (inactive)
monokai-flat, v1.0.1 (inactive)
monokai-seti, v0.7.0 (inactive)
monokai-slate, v0.6.0 (inactive)
nativescript-ng2-atom-snippets, v1.2.0 (active)
neutron-syntax, v0.7.0 (inactive)
neutron-ui, v0.4.0 (inactive)
ng2-snippets, v0.2.2 (active)
nord-atom-syntax, v0.4.0 (inactive)
nord-atom-ui, v0.9.0 (inactive)
open-html-in-browser, v0.1.0 (inactive)
open-recent, v5.0.0 (active)
pigments, v0.38.0 (active)
polymer-snippets, v3.2.1 (inactive)
precss, v0.3.0 (inactive)
Quick-JavaScript, v2.2.0 (active)
script, v3.12.2 (inactive)
seti-icons, v1.3.4 (active)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.3.2 (inactive)
solarized-seti-ui, v0.8.6 (inactive)
titanium-language-javascript, v0.48.0 (inactive)
todo-show, v1.8.0 (inactive)
tron-legacy-syntax, v0.5.0 (inactive)
tron-legacy-theme, v0.8.0 (inactive)
tron-legacy-ui, v0.6.0 (inactive)
tron-theme, v0.3.2 (inactive)
turbo-javascript, v1.4.0 (inactive)
typescript-modules-helper, v0.6.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by ghost** [comment]
@Tikam02 According your logs the path is "colorpicker" and not "color-picker", thats still the old package!
