### ISSUE TITLE
Failed to activate the colorpicker package

### ISSUE THREAD

**Issue by bluekeel** [ardcore/atom-colorpicker#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [colorpicker](https://github.com/ardcore/atom-colorpicker) package, v0.3.0
### Stack Trace

Failed to activate the colorpicker package

```
At Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".


EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

  at Function (native)
  at installColorSpace (/Users/RT/.atom/packages/colorpicker/node_modules/onecolor/one-color-all-debug.js:97:32)
  at Object.<anonymous> (/Users/RT/.atom/packages/colorpicker/node_modules/onecolor/one-color-all-debug.js:218:1)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at /Users/RT/.atom/packages/colorpicker/node_modules/colorjoe/dist/colorjoe.js:3:34
  at Object.<anonymous> (/Users/RT/.atom/packages/colorpicker/node_modules/colorjoe/dist/colorjoe.js:11:2)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/RT/.atom/packages/colorpicker/lib/colorpicker-view.coffee:1:12)
  at Object.<anonymous> (/Users/RT/.atom/packages/colorpicker/lib/colorpicker-view.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/RT/.atom/packages/colorpicker/lib/colorpicker.coffee:1:19)
  at Object.<anonymous> (/Users/RT/.atom/packages/colorpicker/lib/colorpicker.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:672:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/src/package.js:257:12)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:236:14)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:742:29
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:227:20)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```
### Commands

```
     -2:51.7 core:move-up (atom-text-editor.editor.is-focused)
     -2:50.5 core:backspace (atom-text-editor.editor.is-focused)
     -2:49.6 core:move-down (atom-text-editor.editor.is-focused)
     -2:48.9 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -2:48.9 snippets:expand (atom-text-editor.editor.is-focused)
     -2:48.9 editor:indent (atom-text-editor.editor.is-focused)
     -2:48.2 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:44.7 core:move-up (atom-text-editor.editor.is-focused)
     -2:43.6 core:move-down (atom-text-editor.editor.is-focused)
     -2:43.2 core:move-up (atom-text-editor.editor.is-focused)
  2x -2:42.7 core:move-down (atom-text-editor.editor.is-focused)
  4x -2:42.1 editor:newline (atom-text-editor.editor.is-focused)
     -2:11.6 core:backspace (atom-text-editor.editor.is-focused)
     -1:37.8 core:confirm (atom-text-editor.editor.mini)
     -0:41.9 editor:newline (atom-text-editor.editor.is-focused)
     -0:00.6 colorpicker:show (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "remember-session",
      "save-session"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Stylus, v0.6.0
atom-jade, v0.1.0
colorpicker, v0.3.0
language-cfml, v0.5.1
language-expressionengine, v0.2.3
seti-syntax, v0.3.3
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by jamen** [comment]
I've run into this error as well, on Windows.
