### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an al...

### ISSUE THREAD

**Issue by markwylde** [ardcore/atom-colorpicker#7]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.3
**Thrown From**: [colorpicker](https://github.com/ardcore/atom-colorpicker) package, v0.3.0
### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At /Users/mwylde/.atom/packages/colorpicker/node_modules/onecolor/one-color-all-debug.js:97

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

  at Function (native)
  at installColorSpace (/Users/mwylde/.atom/packages/colorpicker/node_modules/onecolor/one-color-all-debug.js:97:32)
  at Object.<anonymous> (/Users/mwylde/.atom/packages/colorpicker/node_modules/onecolor/one-color-all-debug.js:218:1)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at /Users/mwylde/.atom/packages/colorpicker/node_modules/colorjoe/dist/colorjoe.js:3:34
  at Object.<anonymous> (/Users/mwylde/.atom/packages/colorpicker/node_modules/colorjoe/dist/colorjoe.js:11:2)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/mwylde/.atom/packages/colorpicker/lib/colorpicker-view.coffee:1:12)
  at Object.<anonymous> (/Users/mwylde/.atom/packages/colorpicker/lib/colorpicker-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/mwylde/.atom/packages/colorpicker/lib/colorpicker.coffee:1:19)
  at Object.<anonymous> (/Users/mwylde/.atom/packages/colorpicker/lib/colorpicker.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:257:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:163:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:201:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:235:24
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:546:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:369:26
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```
### Commands

```
     -1:22.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:22.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:21.9.0 core:undo (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:19.1.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:17.9.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:16.2.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:15.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:15.8.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  3x -1:08.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:56.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
 16x -0:54.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  7x -0:47.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:45.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:45.6.0 settings-view:install-packages-and-themes (atom-text-editor.editor)
     -0:36.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:33 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "isotope-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
isotope-ui, v2.4.1

# Dev
No dev packages
```

**Comment by markwylde** [comment]
Sorry, duplicate of:
https://github.com/ardcore/atom-colorpicker/issues/5
